### ISSUE TITLE
polyfill `console`

### ISSUE THREAD

**Issue by FND** [complate/complate-spring-mvc#8]
complate is typically used with [faucet](https://github.com/faucet-pipeline), which [reports](https://github.com/faucet-pipeline/faucet-pipeline-js/blob/9ce6eafa58d7b169faab10b829f3826dddede180/lib/util.js#L3) compilation errors directly within the bundle:

```javascript
(typeof alert !== "undefined" ? alert : console.error)("ERROR: SyntaxError: … Unexpected token …");
```

However, Nashorn currently doesn't support `console.error`, using `print` instead (there's no immediate equivalent for stderr AFAIK). Thus, before evaluating JavaScript code, we should prepend the following:

```javascript
if(typeof console === "undefined") {
    var console = {
        log: print,
        error: print
    };
}
```

(Note that we're already doing something similar for `global`.)

**Comment by dwestheide** [comment]
Fixed by #9 .
